### ISSUE TITLE
NTR germ tube 

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#6]
New term request:

(will be) id: FAO:0001026
name: germ tube
def: "the outgrowth that emerges from a spore following release from dormancy. Note that for historical reasons, the term "germ tube" is inappropriately used for the hypha that emerges from a Candida albicans yeast cell that produces new cells in a filamentous form."
synonym: "spore germination tube" EXACT [ ]
xref: GO:0009847
is_a: FAO:0000001 ! fungal structure
develops_from: FAO:0000023 asexual spore
develops_from: FAO:0000017 sexual spore
created_by: dinglis

Please review and comment on whether the information for this proposed term is accurate and acceptable.

@mah11
@tberardini

!

**Comment by dianeoinglis** [comment]
Keep this simple. Instead of 'develops_from' the two types of spores, use 'develops_from: FAO:0000019 spore'

**Comment by mah11** [comment]
Question: Should we include this in FAO? It looks like it's actually part of a cell, rather than a larger anatomical structure - there's a GO cellular component term:

id: GO:0032179
name: germ tube
namespace: cellular_component
def: "The slender tubular outgrowth first produced by most spores in germination." [ISBN:0877799148]
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of CL:0000000 ! cell

@dianeoinglis @Achchuthan @cmungall

**Comment by Achchuthan** [comment]
Hi @mah11,
From my limited fungal knowledge and from what I have read now, it looks like that germ tube is a part of a cell. So, I would agree with you that the representation of germ tube in GO is sufficient.
Thanks,
Achchuthan

**Comment by mah11** [comment]
Thanks, @Achchuthan. I think we can close this, since the GO term will do.
